"""add: removed parent_id column fromQuestion set entity

Revision ID: 0a5b9635fbeb
Revises: 78b97545789b
Create Date: 2025-05-19 19:13:48.997957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a5b9635fbeb'
down_revision: Union[str, None] = '78b97545789b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_sets_parent_id', table_name='question_sets')
    op.drop_column('question_sets', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_sets', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_question_sets_parent_id', 'question_sets', ['parent_id'], unique=False)
    # ### end Alembic commands ###
