"""remove: parent_id column 

Revision ID: 4d22c4ebdd0e
Revises: 80e05c050d04
Create Date: 2025-05-19 18:15:03.275580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d22c4ebdd0e'
down_revision: Union[str, None] = '80e05c050d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_sets_parent_id', table_name='question_sets')
    op.drop_column('question_sets', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_sets', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_question_sets_parent_id', 'question_sets', ['parent_id'], unique=False)
    # ### end Alembic commands ###
