"""add: parent_id column 

Revision ID: 78b97545789b
Revises: 4d22c4ebdd0e
Create Date: 2025-05-19 18:19:18.259172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b97545789b'
down_revision: Union[str, None] = '4d22c4ebdd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_sets', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_question_sets_parent_id'), 'question_sets', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_sets_parent_id'), table_name='question_sets')
    op.drop_column('question_sets', 'parent_id')
    # ### end Alembic commands ###
