"""alter :version,is_active to assement table, add: unique constarint 

Revision ID: 80e05c050d04
Revises: deb27f3a1829
Create Date: 2025-05-19 18:11:38.962461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e05c050d04'
down_revision: Union[str, None] = 'deb27f3a1829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('assessments', sa.Column('version', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_assessment_type_version', 'assessments', ['type_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_assessment_type_version', 'assessments', type_='unique')
    op.drop_column('assessments', 'version')
    op.drop_column('assessments', 'is_active')
    # ### end Alembic commands ###
