"""create assessment_types table and link UserGroup to AssessmentType

Revision ID: fd28f0221159
Revises: 83473f3a1e7d
Create Date: 2025-05-19 15:42:07.519484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd28f0221159'
down_revision: Union[str, None] = '83473f3a1e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_assessment_types_id'), 'assessment_types', ['id'], unique=False)
    op.add_column('user_groups', sa.Column('assessment_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_groups', 'assessment_types', ['assessment_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_column('user_groups', 'assessment_type_id')
    op.drop_index(op.f('ix_assessment_types_id'), table_name='assessment_types')
    op.drop_table('assessment_types')
    # ### end Alembic commands ###
